server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://pg-2ff57b18-alagesan-0eb8.b.aivencloud.com:15331/templeinfo?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://pg-2ff57b18-alagesan-0eb8.b.aivencloud.com:15331/templeinfo?sslmode=require}
    username: ${SPRING_R2DBC_USERNAME:avnadmin}
    password: ${SPRING_R2DBC_PASSWORD:}
  ai:
    mcp:
      server:
        name: springaimcp-server
        version: 1.0.0
        transport: sse
        port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

temple:
  translation:
    gemini-api-key: ${GEMINI_API_KEY:}
